### ISSUE TITLE
can't the script to work

### ISSUE THREAD

**Issue by milanspk** [grayleonard/booxtream-epub-drm-remover#2]
i'm getting SyntaxError: invalid syntax
`File "cure.py", line 37
``print '\n\n === Removing \'Ex Libris\' watermark (WM0) === \n\n'`
`                                                                   ^`
`SyntaxError: invalid syntax`
i don't know what am i doing wrong with the syntax, i tried:
`python cure.py -i original_name.epub -o original_name1.epub`
`python cure.py -i <original_name.epub> -o <original_name1.epub>`
`python cure.py -i <original_name.epub> -o </home/user/>`

tried running as root also.
any help appreciated

**Comment by grayleonard** [comment]
Which version of python are you using? Python 3 throws this error, see [this](http://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python) as to why.

If that's the reason, using python 2.7 should fix the error.

**Comment by milanspk** [comment]
yes, using 2.7 fixes it. i it stops at "Removing 'Disclaimer' watermark" now:
`[wm1] Found disclaimer file: disclaimerOwnerAddress2637.xhtml`
`[searchDirectoryForString] Searching . for disclaimerOwnerAddress2637.xhtml`
`Traceback (most recent call last):`
`  File "cure.py", line 309, in <module>`
`    main(sys.argv[1:])`
`  File "cure.py", line 298, in main`
`    wm1()`
`  File "cure.py", line 76, in wm1`
`    os.remove(disclaimer)`
`OSError: [Errno 2] No such file or directory: 'disclaimerOwnerAddress2637.xhtml'`

**Comment by grayleonard** [comment]
Is it possible for you to send me the file you're working with?

gl7039a@american.edu

**Comment by milanspk** [comment]
sent you the file. i tried with another one, same output

**Comment by milanspk** [comment]
i don't know it this helps, but after after removing references to [wm1] and doing it's job manual, the script works. i noticed then that size of the file doubled and when i edited it i found all the watermarks stayed there but were not linked anymore so after deleting them it seems that i got a clean (and still readable)  book. the only names that stayed the same were some images.

**Comment by grayleonard** [comment]
Hey, just pushed 4afffde, see if that does it for you. Thanks for sending the file -- I tested it and it worked for me. 

The disclaimer file was in the root directory of the .epub on the files I tested, but it wasn't in yours. It seems that the structure of pdf's differ based on when they were created.

Let me know if it works!
