### ISSUE TITLE
Cured epub still contains watermarked image in archive

### ISSUE THREAD

**Issue by lostfictions** [grayleonard/booxtream-epub-drm-remover#5]
Hey there, thanks for this tool! I just tried running it on some books I bought from the Verso sale today and at a first glance it works well -- but when I extracted the epub to take a quick look, there was a watermarked image still present in the archive (even though it seems to have been removed from the page flow.)

(If it's helpful, the DRM seems to be applied even to free PDFs from Verso, like [this one](https://www.versobooks.com/books/1948-feminist-radical-thinkers).)

**Comment by lostfictions** [comment]
Here's a run of `diff.sh` of a free epub downloaded from their site under two different accounts:

![diff](https://user-images.githubusercontent.com/567041/28737011-9b7a602c-73ba-11e7-9eaf-936d881d86e8.png)

**Comment by grayleonard** [comment]
Thanks for reporting, seems to be a bug I introduced from fixing the last issue. Looking at it now.

**Comment by grayleonard** [comment]
Just pushed a fix for this - the watermark image is once again deleted from the repackaged epub, as it was before.

**Comment by lostfictions** [comment]
Thanks for the quick turnaround! (As I mentioned above, upon closer inspection of the cleaned epub there also seems to be some further image watermarking happening that the script doesn't fix, but I'll open a separate issue for that.)
